### ISSUE TITLE
dns.exception.SyntaxError when posting task

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#1178]
On a 4.4.0 host (`lola01.garr.it`), I see this error whenever I try to post a task to pScheduler:

```
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    Exception: ValueError
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    Traceback (most recent call last):
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/inet.py", line 117, in is_multicast
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        first = maybe_ord(dns.ipv4.inet_aton(text)[0])
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/ipv4.py", line 52, in inet_aton
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        raise dns.exception.SyntaxError
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    dns.exception.SyntaxError: Text input is malformed.
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    During handling of the above exception, another exception occurred:
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    Traceback (most recent call last):
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/inet.py", line 121, in is_multicast
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        first = maybe_ord(dns.ipv6.inet_aton(text)[0])
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/ipv6.py", line 155, in inet_aton
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        raise dns.exception.SyntaxError
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    dns.exception.SyntaxError: Text input is malformed.
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    During handling of the above exception, another exception occurred:
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    Traceback (most recent call last):
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        rv = self.dispatch_request()
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        return self.view_functions[rule.endpoint](**req.view_args)
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/var/www/pscheduler-server/pschedulerapiserver/tasks.py", line 694, in tasks_uuid
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        = processor.process(json_in, hints, rewrite=False)
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/limitprocessor.py", line 160, in process
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        identifications = self.identifiers.identities(hints)
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/identifierset.py", line 97, in identities
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        if evaluator.evaluate(hints) and not invert:
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/identifier/ipcymrubogon.py", line 92, in evaluate
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        resolved = self.resolver.query(host, 'A')[0]
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/resolver.py", line 913, in query
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        source_port=source_port)
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/query.py", line 325, in udp
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        q.keyring, q.mac, ignore_trailing)
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/query.py", line 261, in receive_udp
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        (dns.inet.is_multicast(destination[0]) and
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR      File "/usr/lib/python3.6/site-packages/dns/inet.py", line 124, in is_multicast
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR        raise ValueError
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    ValueError
Aug  2 11:40:39 lola01 journal: pscheduler-api ERROR    Internal error 140.105.156.225 POST https://lola01.garr.it/pscheduler/tasks/8b5935cf-57ae-4331-b008-56d66dec7485: Internal problem; see system logs.
```

**Comment by tonin** [comment]
I confirm that it is the default `limits.conf` that is used.  Could it be that this is because the reverse DNS of this host uses [RFC-2317](https://www.rfc-editor.org/rfc/rfc2317.html) format?

**Comment by mfeit-internet2** [comment]
That's a good bet.  Should be an easy fix.

```
$ host 140.105.156.225
225.156.105.140.in-addr.arpa domain name pointer geantsonar.units.it.
$ host lola01.garr.it
lola01.garr.it has address 193.206.127.163
$ host 193.206.127.163
163.127.206.193.in-addr.arpa is an alias for 163.160/28.127.206.193.in-addr.arpa.
163.160/28.127.206.193.in-addr.arpa domain name pointer lola01.garr.it.
```

**Comment by mfeit-internet2** [comment]
Notes:

This is not a problem with the pScheduler code.

Test program, which does what the pScheduler code does:

```
#!/usr/bin/env python3

import dns
import dns.resolver

resolver = dns.resolver.Resolver()

ip = '193.206.127.163'
#ip = "::1"
#ip = "127.0.0.1"

octets = [ octet.decode("ascii")
           for octet in dns.reversename.from_address(ip)[0:-3] ]
host = '.'.join(octets)
host += '.v4.fullbogons.cymru.com' if len(octets) == 4 \
        else '.v6.fullbogons.cymru.com'

print("Resolving", host)

try:
    # This blows up.
    print(resolver.query(host, 'A'))
except (dns.resolver.NXDOMAIN,
        dns.exception.Timeout,
        dns.resolver.NoAnswer,
        dns.resolver.NoNameservers) as ex:
    print("Got allowable exception:", ex)

```

The origin of the problem appears to be in `/usr/lib/python3.6/site-packages/dns/resolver.py`, which is creating something passed to in the call to `udp()` (see `/usr/lib/python3.6/site-packages/dns/query.py`) that `is_multicast()` ultimately doesn't like.

I can't reproduce this problem on my home connection, at Internet2, ESNet or Poznan.  It only happens at GARR, which leads me to believe that something internal to that network may be fiddling with DNS replies.

**Comment by tonin** [comment]
Thanks, this turned out to be a DNS resolver misconfiguration.

**Comment by mfeit-internet2** [comment]
I set the test program above up to read a resolver config that queries ns1.garr.net and grabbed the traffic:

```
[root@lola01 ~]# tcpdump -v -X -i enp3s0 host ns1.garr.net
tcpdump: listening on enp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:20:42.338868 IP (tos 0x0, ttl 64, id 53573, offset 0, flags [DF], proto UDP (17), length 85)
    lola01.garr.it.43020 > ns1.garr.net.domain: 6429+ A? 163.127.206.193.v4.fullbogons.cymru.com. (57)
        0x0000:  4500 0055 d145 4000 4011 d8eb c1ce 7fa3  E..U.E@.@.......
        0x0010:  c1ce 8d26 a80c 0035 0041 2642 191d 0100  ...&...5.A&B....
        0x0020:  0001 0000 0000 0000 0331 3633 0331 3237  .........163.127
        0x0030:  0332 3036 0331 3933 0276 340a 6675 6c6c  .206.193.v4.full
        0x0040:  626f 676f 6e73 0563 796d 7275 0363 6f6d  bogons.cymru.com
        0x0050:  0000 0100 01                             .....
17:20:42.355928 IP (tos 0x0, ttl 61, id 14374, offset 0, flags [none], proto UDP (17), length 155)
    ns1.garr.net.domain > lola01.garr.it.43020: 6429 NXDomain 0/1/0 (127)
        0x0000:  4500 009b 3826 0000 3d11 b4c5 c1ce 8d26  E...8&..=......&
        0x0010:  c1ce 7fa3 0035 a80c 0087 88f8 191d 8183  .....5..........
        0x0020:  0001 0000 0001 0000 0331 3633 0331 3237  .........163.127
        0x0030:  0332 3036 0331 3933 0276 340a 6675 6c6c  .206.193.v4.full
        0x0040:  626f 676f 6e73 0563 796d 7275 0363 6f6d  bogons.cymru.com
        0x0050:  0000 0100 010a 6675 6c6c 626f 676f 6e73  ......fullbogons
        0x0060:  0563 796d 7275 0363 6f6d 0000 0600 0100  .cymru.com......
        0x0070:  001b d700 2609 626f 676f 6e2d 6e73 31c0  ....&.bogon-ns1.
        0x0080:  4403 6e6f 63c0 4461 1132 4b00 0054 6000  D.noc.Da.2K..T`.
        0x0090:  000e 1000 093a 8000 001c 20              .....:.....
```

```
[root@lola01 ~]# tcpdump -v -X -i enp3s0 host 8.8.8.8
tcpdump: listening on enp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:22:02.111137 IP (tos 0x0, ttl 64, id 35189, offset 0, flags [DF], proto UDP (17), length 85)
    lola01.garr.it.48193 > dns.google.domain: 41868+ A? 163.127.206.193.v4.fullbogons.cymru.com. (57)
        0x0000:  4500 0055 8975 4000 4011 5fa1 c1ce 7fa3  E..U.u@.@._.....
        0x0010:  0808 0808 bc41 0035 0041 c682 a38c 0100  .....A.5.A......
        0x0020:  0001 0000 0000 0000 0331 3633 0331 3237  .........163.127
        0x0030:  0332 3036 0331 3933 0276 340a 6675 6c6c  .206.193.v4.full
        0x0040:  626f 676f 6e73 0563 796d 7275 0363 6f6d  bogons.cymru.com
        0x0050:  0000 0100 01                             .....
17:22:02.236241 IP (tos 0x0, ttl 124, id 65172, offset 0, flags [none], proto UDP (17), length 135)
    dns.google.domain > lola01.garr.it.48193: 41868 NXDomain 0/1/0 (107)
        0x0000:  4500 0087 fe94 0000 7c11 ee4f 0808 0808  E.......|..O....
        0x0010:  c1ce 7fa3 0035 bc41 0073 7d0a a38c 8183  .....5.A.s}.....
        0x0020:  0001 0000 0001 0000 0331 3633 0331 3237  .........163.127
        0x0030:  0332 3036 0331 3933 0276 340a 6675 6c6c  .206.193.v4.full
        0x0040:  626f 676f 6e73 0563 796d 7275 0363 6f6d  bogons.cymru.com
        0x0050:  0000 0100 01c0 1f00 0600 0100 0007 0700  ................
        0x0060:  2609 626f 676f 6e2d 6e73 31c0 2a03 6e6f  &.bogon-ns1.*.no
        0x0070:  63c0 2a61 1132 4b00 0054 6000 000e 1000  c.*a.2K..T`.....
        0x0080:  093a 8000 001c 20
```
The packet from n1.garr.net is laid out differently than the one from Google, so it's not that the resolver on lola01 is incorrectly-configured, it's that ns1 is returning bogus data.

I can argue both sides of the debate on what to do here:

 * On one hand, the identifier has a `fail-result` parameter that determines what happens when there's a failure in the resolution process rather than a system of code problem.  This seems like that kind of failure.
 * On the other, the actual fault is external to the code.  Throwing an exception would, ultimately, produce useful diagnostic information but would also torpedo the limit processor, which would reduce reliability.

A happy medium would be to expand what the identifiers return to include that information for inclusion in the limit diagnostics, which is what I think I'm going to do here.  But I'll table it until 5.0 because I think the existing bug fix is good for the time being.
