### ISSUE TITLE
Not specificying a pid file breaks the daemons

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1188]
```
[root@psdev1 pscheduler]# ./pscheduler-server/pscheduler-server/daemons/scheduler --dsn @/etc/pscheduler/database/database-dsn --debug --verbose --pid-file /dev/null
2021-08-05T18:32:12 Debug started
2021-08-05T18:32:12 Started
Traceback (most recent call last):
  File "./pscheduler-server/pscheduler-server/daemons/scheduler", line 939, in <module>
    with pscheduler.PidFile(options.pidfile) as pidfile:
  File "/usr/lib/python3.6/site-packages/pscheduler/pidfile.py", line 33, in __enter__
    self.pidfile.truncate()
OSError: [Errno 22] Invalid argument
```

The default PID file is /dev/null, which no longer appears to work.  Fix this across all daemons.

**Comment by mfeit-internet2** [comment]
This turned out to be a mistake in just one daemon.  Fixed.
