### ISSUE TITLE
Netreach validator dies on None

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1212]
Seen at SC:

```
2021/11/12 11:09:43 WARN pid=28122 prog=perfSONAR_PS::PSConfig::PScheduler::Agent::_run_end line=231 guid=AC414C4C-43E3-11EC-8ED1-678183584AF3 msg=Problem adding test netreach, continuing with rest of config: INTERNAL SERVER ERROR: Unable to validate test spec: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/classes/test/netreach/spec-is-valid", line 19, in <module>
    valid, message = spec_is_valid(json)
  File "/usr/libexec/pscheduler/classes/test/netreach/validate.py", line 88, in spec_is_valid
    network = ipaddress.ip_network(str(json["network"]))
  File "/usr/lib64/python3.6/ipaddress.py", line 84, in ip_network
    address)
ValueError: 'None' does not appear to be an IPv4 or IPv6 network
```

Need to properly reject null values for the network field.

**Comment by mfeit-internet2** [comment]
Not sure how this was getting past JSON validation; initial testing with this data seems to work:

```
{
    "network": null,
    "schema": 1
}
```

Not critical and can be kicked down the road.
