### ISSUE TITLE
Ping parser doesn't handle full loss correctly

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1261]
Don't try to calculate based on `min` if there isn't one:

```
  Tool failed: Traceback (most recent call last):
    File "/usr/libexec/pscheduler/classes/tool/ping/run", line 274, in <module>
      parsed_results = pscheduler.parse_ping(stdout, count)
    File "/usr/lib/python3.6/site-packages/pscheduler/ping.py", line 162, in parse_ping
      datetime.timedelta(seconds=float(min)/1000.0) ),
  UnboundLocalError: local variable 'min' referenced before assignment
```

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Corrected an internal problem that caused the `ping` tool to not return a result in the face of 100% packet loss.
