### ISSUE TITLE
Failed to validate limit: Process took too long to run

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#1276]
From time to time I'm seeing this error in the pscheduler.log. Not sure if this is related to #1273 . Anyway the message in the log asks to report it:
```
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO     Forbade 217.147.227.163 POST https://psmall-poz1.man.poznan.pl/pscheduler/tasks/41ca5066-628f-4a79-abf0-7d2cc5529d9b: Task forbidden by limits:
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO     Failed to process limits: processor threw an exception.
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO     Traceback (most recent call last):
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/limitprocessor.py", line 262, in process
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         return self._process(task, hints, rewrite, prioritize)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/limitprocessor.py", line 188, in _process
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         = self.applications.check(proposal, classifications, check_schedule)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/applicationset.py", line 225, in check
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         check_schedule)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/applicationset.py", line 161, in __check_application
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         = self.__check_group(proposal, group, check_schedule)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/applicationset.py", line 119, in __check_group
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         evaluated = self.limits.check(proposal, limit, check_schedule)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/limitset.py", line 166, in check
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         evaluated = evaluator.evaluate(proposal)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO       File "/usr/lib/python3.6/site-packages/pscheduler/limitprocessor/limit/test.py", line 86, in evaluate
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO         raise RuntimeError("Failed to validate limit: %s" % stderr)
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO     RuntimeError: Failed to validate limit: Process took too long to run.
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO
Apr 12 08:42:10 psmall-poz1 journal: pscheduler-api INFO     Please report this as a bug.
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR    Exception: psycopg2.InternalError: Unable to get participant data: Process took too long to run.
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR    Traceback (most recent call last):
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR      File "/var/www/pscheduler-server/pschedulerapiserver/runs.py", line 437, in tasks_uuid_runs_run
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR        onerow=True)
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR      File "/var/www/pscheduler-server/pschedulerapiserver/dbcursor.py", line 112, in dbcursor_query
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR        raise ex
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR      File "/var/www/pscheduler-server/pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR        cursor.execute(query, args)
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR    psycopg2.InternalError: Unable to get participant data: Process took too long to run.
Apr 12 08:42:12 psmall-poz1 journal: pscheduler-api ERROR    Internal error 217.147.227.163 PUT https://psmall-poz1.man.poznan.pl/pscheduler/tasks/b8a37615-338d-4665-aef8-2c898fec62b8/runs/489ea8de-7ad7-4bec-860a-6433e568e091: Unable to get participant data: Process took too long to run.

```

**Comment by mfeit-internet2** [comment]
Usually when you bump into errors like `Process took too long to run`, it's a sign that the system got too busy to execute things in time.

This is semi-related to #1273; it's the same problem but in that case there shouldn't be any attempt to run a process.

**Comment by szymontrocha** [comment]
Yeah, it's just full error output comparing to others formatted error messages and it explicitely said "Please report this as a bug" so I did that.
