### ISSUE TITLE
pscheduler troubleshoot on U20 throws error when trying to use traceroute6

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#1341]
When running `pscheduler troubleshoot` on Ubuntu 20, you get the following error:
```
gpejovic@eqxch2-ps:~$ pscheduler troubleshoot
Performing basic troubleshooting of eqxch2-ps.es.net.

eqxch2-ps.es.net:

  Measuring MTU... Unsafe or unknown: Error: FileNotFoundError: [Errno 2] No such file or directory: 'tracepath6'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pscheduler/program.py", line 182, in run_program
    process = __get_process(argv, new_env, attempts)
  File "/usr/lib/python3/dist-packages/pscheduler/program.py", line 174, in __get_process
    raise ex
  File "/usr/lib/python3/dist-packages/pscheduler/program.py", line 164, in __get_process
    return subprocess.Popen(argv,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tracepath6'
  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... OK.
  Exercising API... Archivers... Contexts... Tests... Tools... OK.
  Fetching service status... OK.
  Checking services... Ticker... Scheduler... Runner... Archiver... OK.
  Checking limits... OK.
  Idle test.... 5 seconds... Finished... Checking archiving... OK.

pScheduler appears to be functioning normally.
```

The issue is that on U20 there is no tracepath6, instead it expects `tracepath -6 ...`. The problematic area is likely in mtu.py at:

```
    if ipversion == 6:
        tracepath = "tracepath6"
    else:
        tracepath = "tracepath"
```

**Comment by mfeit-internet2** [comment]
...and, of course, there are differences between what's in EL and Debian.  I'll have to add code to figure out which program is available and invoke it appropriately.

**Comment by mfeit-internet2** [comment]
It looks like `-4` and `-6` are present on EL8 and EL9 but not EL7.  I can make the tool smart enough to figure out which style to use.

**Comment by mfeit-internet2** [comment]
Check code starting here and see if the oldest version of Debian/Ubuntu we support needs this.  EL7 still needs it.

https://github.com/perfsonar/pscheduler/blob/6991a3c4de9098ac0341dce0cfb0b2920d0a27e3/pscheduler-tool-tracepath/tracepath/run#L77

**Comment by mfeit-internet2** [comment]
Realized that I fixed `pscheduler-tool-tracepath` (which needed the fix as well) and not the code used by the troubleshooter.  Fixed that, too.
