### ISSUE TITLE
Broken Pipe During HTTP Archiving

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1367]
Marian observed the following in the archiver logs that may be a result of a lost connection to the HTTP server.  (I think Abigail added code to keep connections up at some point.  That may need to be made more-robust.)

```
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR    Traceback (most recent call last):
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR      File "/usr/libexec/pscheduler/classes/archiver/http/archive", line 207, in <module>
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR      File "/usr/libexec/pscheduler/classes/archiver/http/archive", line 207, in <module>
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR        EMITTER(archive(parsed))
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR        EMITTER(archive(parsed))
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/psjson.py", line 202, in __call__
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/psjson.py", line 202, in __call__
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR        self.emit_text(json_dump(json, pretty=False))
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR        self.emit_text(json_dump(json, pretty=False))
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/psjson.py", line 197, in emit_text
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR      File "/usr/lib/python3.6/site-packages/pscheduler/psjson.py", line 197, in emit_text
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR        self.handle.flush()
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR        self.handle.flush()
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR    BrokenPipeError: [Errno 32] Broken pipe
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR    BrokenPipeError: [Errno 32] Broken pipe
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR    Exception: BrokenPipeError: [Errno 32] Broken pipe
Nov 28 10:08:40 psb02-gva archiver-http/archive ERROR    Exception: BrokenPipeError: [Errno 32] Broken pipe
```

Archive config:

```
            {
               "ttl" : "P2DT1H",
               "data" : {
                  "retry-policy" : [
                     {
                        "wait" : "PT1M",
                        "attempts" : 5
                     },
                     {
                        "wait" : "PT5M",
                        "attempts" : 11
                     },
                     {
                        "wait" : "PT1H",
                        "attempts" : 23
                     },
                     {
                        "wait" : "PT4H",
                        "attempts" : 6
                     }
                  ],
                  "op" : "post",
                  "_url" : "https://ps-collection.atlas-ml.org/"
               },
               "archiver" : "http"
            }
```

**Comment by mfeit-internet2** [comment]
This appears to be the pipe where the _result_ is written breaking, probably because the parent process exited.  Probably not a problem with the plugin.
