### ISSUE TITLE
pScheduler with Python 3.11

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/pscheduler#1370]
Running pScheduler on Debian 12 which has Python 3.11 I see the following errors:

```
root@2a2501b2df8f:/# pscheduler troubleshoot
/usr/lib/pscheduler/commands/troubleshoot:17: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Performing basic troubleshooting of 2a2501b2df8f.

2a2501b2df8f:

  Measuring MTU... Unsafe or unknown: Error: AttributeError: module 'collections' has no attribute 'Callable'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pscheduler/program.py", line 184, in run_program
    __running_add(process)
  File "/usr/lib/python3/dist-packages/pscheduler/program.py", line 72, in __running_add
    __init_running()
  File "/usr/lib/python3/dist-packages/pscheduler/program.py", line 46, in __init_running
    on_graceful_exit(__terminate_running)
  File "/usr/lib/python3/dist-packages/pscheduler/exit.py", line 49, in on_graceful_exit
    if not isinstance(call, collections.Callable):
                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... Unsynchronized (Not considered fatal)
  Exercising API... Archivers... Contexts... Tests... Tools... OK.
  Fetching service status... OK.
  Checking services...Traceback (most recent call last):
  File "/usr/lib/pscheduler/commands/troubleshoot", line 524, in <module>
    check_service_status(api)
  File "/usr/lib/pscheduler/commands/troubleshoot", line 247, in check_service_status
    service_status = status["services"][service]
                     ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'ticker'
root@2a2501b2df8f:/# python3 --version
Python 3.11.2
```

**Comment by mfeit-internet2** [comment]
Everything listed here has been corrected.  I'm probably going to start going through the Python code with PyLint and some other utilities to find things that are deprecated.
