### ISSUE TITLE
Tracepath runner throwing exceptions

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1376]
Seen at CERN.  Might be that the content of tracepath's output has changed.

```
Dec 11 16:02:16 psb02-gva runner ERROR    106479: Run failed 1: Traceback (most recent call last):
Dec 11 16:02:16 psb02-gva runner ERROR      File "/usr/lib/python3.6/site-packages/icmperror/icmperror.py", line 56, in translate
Dec 11 16:02:16 psb02-gva runner ERROR    106479: Run failed 1: Traceback (most recent call last):
Dec 11 16:02:16 psb02-gva runner ERROR      File "/usr/lib/python3.6/site-packages/icmperror/icmperror.py", line 56, in translate
Dec 11 16:02:16 psb02-gva runner ERROR        return icmp_errors[code]
Dec 11 16:02:16 psb02-gva runner ERROR    KeyError: 'A'
Dec 11 16:02:16 psb02-gva runner ERROR        return icmp_errors[code]
Dec 11 16:02:16 psb02-gva runner ERROR    KeyError: 'A'
Dec 11 16:02:16 psb02-gva runner ERROR    During handling of the above exception, another exception occurred:
Dec 11 16:02:16 psb02-gva runner ERROR    During handling of the above exception, another exception occurred:
Dec 11 16:02:16 psb02-gva runner ERROR    Traceback (most recent call last):
Dec 11 16:02:16 psb02-gva runner ERROR    Traceback (most recent call last):
Dec 11 16:02:16 psb02-gva runner ERROR      File "/usr/libexec/pscheduler/classes/tool/tracepath/run", line 205, in <module>
Dec 11 16:02:16 psb02-gva runner ERROR      File "/usr/libexec/pscheduler/classes/tool/tracepath/run", line 205, in <module>
Dec 11 16:02:16 psb02-gva runner ERROR        hop['error'] = icmperror.translate(matches.group(1))
Dec 11 16:02:16 psb02-gva runner ERROR        hop['error'] = icmperror.translate(matches.group(1))
Dec 11 16:02:16 psb02-gva runner ERROR      File "/usr/lib/python3.6/site-packages/icmperror/icmperror.py", line 58, in translate
Dec 11 16:02:16 psb02-gva runner ERROR      File "/usr/lib/python3.6/site-packages/icmperror/icmperror.py", line 58, in translate
Dec 11 16:02:16 psb02-gva runner ERROR        raise ValueError("Code is not valid")
Dec 11 16:02:16 psb02-gva runner ERROR        raise ValueError("Code is not valid")
Dec 11 16:02:16 psb02-gva runner ERROR    ValueError: Code is not valid
Dec 11 16:02:16 psb02-gva runner ERROR    ValueError: Code is not valid

```

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added support for additional traceroute error codes.
