### ISSUE TITLE
CLI doesn't always fetch the first run.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#24]
CLI occasionally runs into a situation where it fails to fetch the first run.  May be a race condition.

May also have to do with CentOS 7.  Doesn't happen on 6.

-----
Client output:
```
pscheduler task trace --dest www.perfsonar.net --as

WARNING:  This program is still experimental.  Expect it not to work.

This task will be led by dev7
Task URL is http://dev7/pscheduler/tasks/abe37d8a-9449-4e3d-8351-19ed2971cd4a
Fetching first run...
Failed to fetch run: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```
-----
Error internal to REST API:

```
mod_wsgi (pid=14297): Exception occurred processing WSGI script '/var/www/pscheduler-api-server/pscheduler-api-server.wsgi'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./pschedulerapiserver/runs.py", line 76, in tasks_uuid_runs
  File "./pschedulerapiserver/json.py", line 36, in json_query_simple
ProgrammingError: no results to fetch
```

**Comment by mfeit-internet2** [comment]
Further info; not particularly helpful:  https://github.com/psycopg/psycopg2/issues/346

**Comment by mfeit-internet2** [comment]
This seems to have been related to the scheduler not doing its job properly, and the reliability improvements probably did the trick.
