### ISSUE TITLE
Exception text being used as URL in url_delete

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#254]
@igarny and others have observed errors like this:

```
Jan 12 15:12:12 psps-test2-mgmt safe_run/scheduler ERROR    Exception: MissingSchema: Invalid URL u"'Response' object is not iterable\n": No schema supplied. Perhaps you meant http://'Response' object is not iterable
?
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run
    function()
  File "/usr/libexec/pscheduler/daemons/scheduler", line 453, in <lambda>
    pscheduler.safe_run(lambda: main_program())
  File "/usr/libexec/pscheduler/daemons/scheduler", line 409, in main_program
    run_post(url, trynext, log)
  File "/usr/libexec/pscheduler/daemons/scheduler", line 293, in run_post
    pscheduler.url_delete_list(runs_posted)
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 175, in url_delete_list
    return [ url_delete(url, throw=False, timeout=timeout) for url in urls ]
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 151, in url_delete
    request = requests.delete(url, verify=verify_keys, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 146, in delete
    return request('delete', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 361, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
MissingSchema: Invalid URL u"'Response' object is not iterable\n": No schema supplied. Perhaps you meant http://'Response' object is not iterable
?
Jan 12 15:12:12 psps-test2-mgmt safe_run/scheduler ERROR    Waiting 1.0 seconds before restarting
Jan 12 15:12:13 psps-test2-mgmt safe_run/scheduler ERROR    Restarting



Jan 13 15:34:14 psps-test2-mgmt safe_run/scheduler ERROR    Exception: MissingSchema: Invalid URL u"'Response' object is not iterable\n": No schema supplied. Perhaps you meant http://'Res
ponse' object is not iterable
?
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run
    function()
  Fi
le "/usr/libexec/pscheduler/daemons/scheduler", line 453, in <lambda>
    pscheduler.safe_run(lambda: main_program())
  File "/usr/libexec/pscheduler/daemons/scheduler", line 409, i
n main_program
    run_post(url, trynext, log)
  File "/usr/libexec/pscheduler/daemons/scheduler", line 315, in run_post
    pscheduler.url_delete_list(runs_posted)
  File "/u
sr/lib/python2.6/site-packages/pscheduler/psurl.py", line 175, in url_delete_list
    return [ url_delete(url, throw=False, timeout=timeout) for url in urls ]
  File "/usr/lib/pytho
n2.6/site-packages/pscheduler/psurl.py", line 151, in url_delete
    request = requests.delete(url, verify=verify_keys, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/req
uests/api.py", line 146, in delete
    return request('delete', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = sessi
on.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/us
r/lib/python2.6/site-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.6/site-packages/requests
/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 361, in prepare_url
    "Perhaps you meant
http://{0}?".format(url))
MissingSchema: Invalid URL u"'Response' object is not iterable\n": No schema supplied. Perhaps you meant http://'Response' object is not iterable
?
Jan 13 15:34:14 psps-test2-mgmt safe_run/scheduler ERROR    Waiting 3.25 seconds before restarting
```

**Comment by mfeit-internet2** [comment]
Related, seen by Andy:

```
Jan 15 12:19:13 antg-dev safe_run/scheduler ERROR    Exception: InvalidSchema: No connection adapters were found for 'Run would re\
sult in a scheduling conflict.
CONTEXT:  SQL statement "WITH inserted_row AS (
        INSERT INTO run (uuid, task, times, state, errors)
        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
        RETURNING *
    ) SELECT               uuid FROM inserted_row"
PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement

'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run
    function()
  File "/usr/libexec/pscheduler/daemons/scheduler", line 453, in <lambda>
    pscheduler.safe_run(lambda: main_program())
  File "/usr/libexec/pscheduler/daemons/scheduler", line 409, in main_program
    run_post(url, trynext, log)
  File "/usr/libexec/pscheduler/daemons/scheduler", line 293, in run_post
    pscheduler.url_delete_list(runs_posted)
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 175, in url_delete_list
    return [ url_delete(url, throw=False, timeout=timeout) for url in urls ]
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 151, in url_delete
    request = requests.delete(url, verify=verify_keys, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 145, in delete
    return request('delete', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 570, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 644, in get_adapter
    raise InvalidSchema("No con  
```

**Comment by mfeit-internet2** [comment]
d87691f fixes the problem Andy observed.

**Comment by mfeit-internet2** [comment]
Still having problems with something causing scheduling conflicts; but this problem is fixed.
