### ISSUE TITLE
Broken pipe errors while posting runs through the API

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#255]
@tonin and others have observed the following error:

```
Jan 13 15:50:16 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Unable to get participant data: OSError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pscheduler/program.py", line 99, in run_program
    stdout, stderr = process.communicate(stdin, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 927, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1713, in _communicate
    orig_timeout)
  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1797, in _communicate_with_poll
    self._input_offset += os.write(fd, chunk)
OSError: [Errno 32] Broken pipe
CONTEXT:  PL/pgSQL function run_alter() line 118 at RAISE
SQL statement "WITH inserted_row AS (
        INSERT INTO run (uuid, task, times, state, errors)
        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
        RETURNING *
    ) SELECT               uuid FROM inserted_row"
PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement

Traceback (most recent call last):
  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query
    cursor.execute(query, args)
InternalError: Unable to get participant data: OSError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pscheduler/program.py", line 99, in run_program
    stdout, stderr = process.communicate(stdin, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 927, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1713, in _communicate
    orig_timeout)
  File "/usr/lib/python2.7/dist-packages/subprocess32.py", line 1797, in _communicate_with_poll
    self._input_offset += os.write(fd, chunk)
OSError: [Errno 32] Broken pipe
CONTEXT:  PL/pgSQL function run_alter() line 118 at RAISE
SQL statement "WITH inserted_row AS (
        INSERT INTO run (uuid, task, times, state, errors)
        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
        RETURNING *
    ) SELECT               uuid FROM inserted_row"
PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
```

**Comment by mfeit-internet2** [comment]
Seems to be gone, probably tuned out.

**Comment by mfeit-internet2** [comment]
Reopening because of #322.

Need to put `SIGPIPE` protection into `run_program()`.

**Comment by mfeit-internet2** [comment]
See commit above.  Ended up subclassing `subprocess32.Popen` and making an adjustment to one of the internal methods that handles writing to closed pipes by doing a proper close and unregister on the file descriptor.
