### ISSUE TITLE
excessive runs?

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#273]
While looking through some of the throughput errors, I came across this observation:

Task spec:
https://ma-dev2.bldc.grnoc.iu.edu/pscheduler/tasks/5ccc9e0a-7950-4a0e-9e94-228a0c90708a/runs

Note it's a 24 hour task, 2 hour repeat interval

Runs listing:
https://ma-dev2.bldc.grnoc.iu.edu/pscheduler/tasks/5ccc9e0a-7950-4a0e-9e94-228a0c90708a/runs

There are a lot of runs. With the given slip I think you could expect up to around 16 possible runs in that timeframe, but we have way more than that listed here. A good number of them are listed as non-starters.

After talking with Mark, he asked that I file this issue on it. It's possible this is related to the throughput issues. We are also going to work on standing up some more multiparticipant tests to help troubleshoot this as well.

**Comment by mfeit-internet2** [comment]
Was able to duplicate the problem on my dev system.  Notes:

This only seems to happen when there's slip and randslip present.

All of the actual runs are properly scheduled, but for some reason the scheduler attempts to schedule a bunch more well before the start time.

This could be a case of the `try_next` for repeaters with runs pulling out candidates that don't have anything scheduled within the next iteration time for the scheduler.

**Comment by bltierney** [comment]
also seeing this for iperf3:

2017-02-13T07:10:47-08:00 - 2017-02-13T07:11:06-08:00  (Non-Starter)
2017-02-13T07:10:47-08:00 - 2017-02-13T07:11:06-08:00  (Non-Starter)
2017-02-13T07:10:48-08:00 - 2017-02-13T07:11:07-08:00  (Non-Starter)
2017-02-13T07:10:48-08:00 - 2017-02-13T07:11:07-08:00  (Non-Starter)
2017-02-13T07:10:48-08:00 - 2017-02-13T07:11:07-08:00  (Non-Starter)
2017-02-13T07:10:48-08:00 - 2017-02-13T07:11:07-08:00  (Non-Starter)
2017-02-13T07:10:49-08:00 - 2017-02-13T07:11:08-08:00  (Non-Starter)
2017-02-13T07:10:49-08:00 - 2017-02-13T07:11:08-08:00  (Non-Starter)
2017-02-13T07:10:49-08:00 - 2017-02-13T07:11:08-08:00  (Non-Starter)

**Comment by bltierney** [comment]
Might this be related, or a separate issue?  I'm seeing LOTS of these in my logs too:
Feb 13 11:40:19 test-pt1 journal: pscheduler-api ERROR    Exception: InternalError: Run would result in a scheduling conflict.#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/runs.py", line 440, in tasks_uuid_runs_run#012  File "./pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012InternalError: Run would result in a scheduling conflict.#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement

**Comment by mfeit-internet2** [comment]
Notes:

Confirmed:
 * The query behind `schedule_runs_to_schedule` is allowing this to happen, but not always.
 * Happening in the repeating tasks with runs subquery.


Also observed that these are all throughput tests.  Might not be relevant.
```
pscheduler=> select added, start, id, runs, test from task where runs > 2000 order by added;
             added             |         start          |  id   |  runs  | test 
-------------------------------+------------------------+-------+--------+------
 2017-02-08 18:50:01.507149-05 |                        | 10349 |  20148 |    2
 2017-02-09 11:02:38.489444-05 | 2017-02-09 16:57:07-05 | 10438 | 103447 |    2
 2017-02-12 10:48:55.388291-05 | 2017-02-12 16:57:07-05 | 10761 | 135147 |    2
 2017-02-13 17:05:33.703127-05 |                        | 10881 |  34919 |    2
 2017-02-13 23:25:11.729808-05 |                        | 10906 |  15649 |    2
 2017-02-14 05:16:04.629749-05 | 2017-02-14 11:03:36-05 | 10949 |  12696 |    2
 2017-02-14 21:56:42.302138-05 | 2017-02-15 03:50:48-05 | 11088 |   2178 |    2
 2017-02-15 00:54:40.02384-05  | 2017-02-15 06:53:45-05 | 11097 | 170450 |    2
```
The ones with very large numbers of runs may be the ones that go for 24 hours.
