### ISSUE TITLE
Allow for clock slop in scheduling horizon

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#293]
The scheduler may be trying to schedule runs with participants where the start time is just outside the horizon because of clock errors.  Add some tolerance for that in `run_alter`.  Maybe make it configurable.

From Slack:

```
vvidic [9:27 AM] 
2017-02-08 15:26:49 CET [2644-1] pscheduler@pscheduler ERROR:  Cannot schedule runs more than 1 day in advance
2017-02-08 15:26:49 CET [2644-2] pscheduler@pscheduler CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE
       SQL statement "WITH inserted_row AS (
               INSERT INTO run (uuid, task, times, state, errors)
               VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
               RETURNING *
           ) SELECT               uuid FROM inserted_row"
       PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
2017-02-08 15:26:49 CET [2644-3] pscheduler@pscheduler STATEMENT:  SELECT api_run_post('3e3b01b6-71be-4bb5-a1ca-4c5acbe0f13e', '2017-02-09T15:34:10+01:00'::timestamptz, NULL, NULL)

[9:27]  
is this some kind of timezone problem?

[9:30]  
guess not as the date uses +0100

[9:31]  
it really was more than one day in advance at that point

mfeit [9:33 AM] 
All of the date calculations are done with timezone-aware types.

[9:35]  
Could also be that the clock on one of the machines is off just far enough that the run would be just outside the valid range.
```

**Comment by tonin** [comment]
I'm also seeing a lot of those today
```
Feb  9 15:26:57 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
```

**Comment by mfeit-internet2** [comment]
I did find and fix a mistake in the database code where the time horizon check was being made against the actual current time as opposed to the quantized-to-the-second value that gets used everywhere else.  The participants provide the scheduler with a (quantized) list of available time ranges to pick from, so I'm guessing this was probably something that bumped the edge, so this is probably what caused it.  The error message has been expanded to include the amount of time past the horizon was in the request.

@tonin Keep an eye out for more of these and let me know if you see them.

**Comment by tonin** [comment]
Just seen a few more
```
Feb 10 14:51:59 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:03:38 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:03:38 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 10 14:52:02 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:00:09 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:00:09 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 10 14:52:06 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:01:54 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012    cursor.execute(query, args)#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:01:54 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
```

**Comment by tonin** [comment]
And still seeing some, usually with 1 to 10 minutes outside the range:
```
Feb 13 16:16:12 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:02:21 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:02:21 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 13 16:16:13 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:07:46 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:07:46 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 13 16:16:13 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:08:05 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012    cursor.execute(query, args)#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:08:05 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
```

**Comment by mfeit-internet2** [comment]
`1 day 00:01:54 outside the range`

I'm seeing the same on perfsonardev0.  This might be the API not truncating values that go beyond the scheduling horizon.

**Comment by tonin** [comment]
And still seeing quite a few of those (exactly 1475 since midnight CET), usually with 1 to 10 minutes outside the range:
```
Feb 17 10:43:36 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:09:55 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012    cursor.execute(query, args)#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:09:55 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 17 10:43:36 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:09:55 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:09:55 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 17 10:43:38 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:05:56 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012    cursor.execute(query, args)#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:05:56 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
Feb 17 10:43:38 ps-4-0 pscheduler-api ERROR    Exception: InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:05:56 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement#012#012Traceback (most recent call last):#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 159, in tasks_uuid_runs#012    [task, start_time, diags], onerow=True)#012  File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 108, in dbcursor_query#012    raise ex;#012InternalError: Cannot schedule runs more than 1 day in advance (1 day 00:05:56 outside the range)#012CONTEXT:  PL/pgSQL function run_alter() line 37 at RAISE#012SQL statement "WITH inserted_row AS (#012        INSERT INTO run (uuid, task, times, state, errors)#012        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)#012        RETURNING *#012    ) SELECT               uuid FROM inserted_row"#012PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement
```

Also, is it intended that the error messages are printed twice in the `pscheduler.log`, once from `dbcursor.py` and another one from `runs.py` ?

**Comment by mfeit-internet2** [comment]
I haven't made any changes related to this bug yet; watch for commits.

The duplication is expected; when the exception gets thrown in the database code, I log it in case its caller doesn't.  I might be able to find a nice way to deduplicate that, but not before RC3.

**Comment by mfeit-internet2** [comment]
Andy and Ivan noticed that this complaint is happening even when the start/end times are clearly within the boundaries:
```
{

    "duration": "PT16S",
    "end-time": "2017-02-17T16:26:28+01:00",
    "errors": "Failed to post lead run: Cannot schedule runs more than 1 day in advance (1 day 00:08:47 outside the range)\nCONTEXT:  SQL statement \"WITH inserted_row AS (\n        INSERT INTO run (uuid, task, times, state, errors)\n        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)\n        RETURNING *\n    ) SELECT               uuid FROM inserted_row\"\nPL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement\n\n",
    "href": "https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/4c22ea33-60fb-4f95-a257-de7e88247b29/runs/507002e9-2ed4-47e4-ac53-5a358a353869",
    "participant": 0,
    "participant-data": { },
    "participant-data-full": null,
    "participants": [
        "psps-test2-mgmt.rrze.uni-erlangen.de"
    ],
    "result": null,
    "result-full": null,
    "result-href": "https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/4c22ea33-60fb-4f95-a257-de7e88247b29/runs/507002e9-2ed4-47e4-ac53-5a358a353869/result",
    "result-merged": null,
    "start-time": "2017-02-17T16:26:12+01:00",
    "state": "nonstart",
    "state-display": "Non-Starter",
    "task-href": "https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/4c22ea33-60fb-4f95-a257-de7e88247b29"
}
```

**Comment by mfeit-internet2** [comment]
This turned out to be improper clamping of proposed run times to the scheduling horizon.

Fixed in 2db553a1bfdd1baebfe1e6e5db78d1c9bfee0209.  Will monitor over the weekend and close if it looks good.

**Comment by mfeit-internet2** [comment]
Still seeing some of these as of two days ago but in smaller numbers.  May be old software still in the test bed?

**Comment by mfeit-internet2** [comment]
This seems to have died off.  Hosts in the U.S. haven't shown this since February 22; the RRZE system shows the 23rd, which could just be a side effect of the time difference.  

To check the logs for dates having it:
```
fgrep -h 'Cannot schedule runs' /var/log/pscheduler/* | awk '{print $2, $1 }' | sort -n | uniq
```

I'm inclined to close this.
