### ISSUE TITLE
HTTP failures cause ticker to die

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#317]
The ticker is catching and restarting on an exception from `http_queue_process()` in the database.  Looks like `pscheduler.url_delete()` may be throwing even when told not to.

```
Exception: InternalError: plpy.Error: Failed to DELETE https://131.243.24.11/pscheduler/tasks/a4b0d3c8-f56c-400b-922c-4a7709a0367d: ('Connection aborted.', error(110, 'Connection timed out'))
CONTEXT:  Traceback (most recent call last):
  PL/Python function "http_delete", line 8, in <module>
    plpy.error("Failed to DELETE %s: %s" % (url, str(ex)))
PL/Python function "http_delete"
PL/pgSQL function http_queue_process(bigint) line 18 at assignment
SQL statement "SELECT http_queue_process(id) FROM http_queue WHERE next_attempt < now()"
PL/pgSQL function http_queue_maint_minute() line 3 at PERFORM
SQL statement "SELECT http_queue_maint_minute()"
PL/pgSQL function ticker_minute() line 4 at PERFORM
SQL statement "SELECT ticker_minute()"
PL/pgSQL function ticker() line 11 at PERFORM

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run
    function()
  File "/usr/libexec/pscheduler/daemons/ticker", line 100, in <lambda>
    pscheduler.safe_run(lambda: main_program())
  File "/usr/libexec/pscheduler/daemons/ticker", line 80, in main_program
    cursor.execute("SELECT ticker()")
InternalError: plpy.Error: Failed to DELETE https://131.243.24.11/pscheduler/tasks/a4b0d3c8-f56c-400b-922c-4a7709a0367d: ('Connecti\
on aborted.', error(110, 'Connection timed out'))
CONTEXT:  Traceback (most recent call last):
  PL/Python function "http_delete", line 8, in <module>
    plpy.error("Failed to DELETE %s: %s" % (url, str(ex)))
PL/Python function "http_delete"
PL/pgSQL function http_queue_process(bigint) line 18 at assignment
SQL statement "SELECT http_queue_process(id) FROM http_queue WHERE next_attempt < now()"
PL/pgSQL function http_queue_maint_minute() line 3 at PERFORM
SQL statement "SELECT http_queue_maint_minute()"
PL/pgSQL function ticker_minute() line 4 at PERFORM
SQL statement "SELECT ticker_minute()"
PL/pgSQL function ticker() line 1

```

**Comment by mfeit-internet2** [comment]
d8c95e603ae34d26b51b3a746daa468bd941bd2d should take care of it.
