### ISSUE TITLE
Resolver Not Handing No-Answer Answers

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#336]
Daniel Spisak observed this:

```
Mar  1 00:00:42 testpoint1-centos-71 journal: runner INFO     619: Run failed 1: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/ping/run", line 433, in <module>
    revmap = pscheduler.dns_bulk_resolve(ips, reverse=True, threads=len(roundtrips))
  File "/usr/lib/python2.7/site-packages/pscheduler/psdns.py", line 195, in dns_bulk_resolve
    chunksize=1):
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
    raise value
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: 4.128.28.172.in-addr.arpa. IN PTR
```

Need to make the resolver function handle that eventuality.

**Comment by mfeit-internet2** [comment]
Missed one in the list of exceptions the reverse resolver quietly swallows.
