### ISSUE TITLE
Package python-jsonschema 2.5.1 for Debian

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#407]
Up to now we were using 2.3.0 that was standard in Jessie (and backported to wheezy).  It seems it is not fully compatible with some pscheduler features and generating this kind of errors:
```
2017-04-12T11:45:47 {"dest": "ps-d8.eshango.net", "timeout": "30", "schema": 1}
Unable to determine the lead participant: Traceback (most recent call last):
  File "/usr/lib/pscheduler/commands/../classes/test/clock/participants", line 15, in <module>
    valid, message = spec_is_valid(json)
  File "/usr/lib/pscheduler/classes/test/clock/validate.py", line 22, in spec_is_valid
    return json_validate(json, schema)
  File "/usr/lib/python2.7/dist-packages/pscheduler/jsonval.py", line 776, in json_validate
    '/' + ('/'.join([str(x) for x in ex.absolute_path])),
AttributeError: 'ValidationError' object has no attribute 'absolute_path'
```

2.5.1 is what is contained in the pscheduler repo, we need to ship that for both Wheezy and Jessie.

If it is of any help, jessie-backports has [this version of the package](https://packages.debian.org/jessie-backports/python-jsonschema).

**Comment by mfeit-internet2** [comment]
See #406

**Comment by tonin** [comment]
duplicate of #406
