### ISSUE TITLE
pscheduler monitor returns error if screen too small

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#412]
It appears if my screen is not tall enough I get the following error:

pscheduler monitor
Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/monitor", line 269, in <module>
    update_tasks(task_window)
  File "/usr/libexec/pscheduler/commands/monitor", line 172, in update_tasks
    assert rows_left >= 0, "Left = %d" % rows_left
AssertionError: Left = -22
[rootal@antg-staging ~]# pscheduler monitor
Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/monitor", line 284, in <module>
    update_tasks(task_window)
  File "/usr/libexec/pscheduler/commands/monitor", line 172, in update_tasks
    assert rows_left >= 0, "Left = %d" % rows_left
AssertionError: Left = -22

This was on a CentOS 7 host (antg-staging.es.net).

**Comment by mfeit-internet2** [comment]
This looks like it happens when the screen is resized during an update.
