### ISSUE TITLE
AS Bulk Resolver Missing Exception

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#415]
This run of the traceroute tool shows the exception below:

https://perf-rcc.unh.edu/pscheduler/tasks/4e264099-b22b-4002-acf1-01f9eaec0a35/runs/a48b6fdc-ead2-46f6-a7a0-af62080b6c3

```
Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/traceroute/run", line 388, in <module>
    ases = pscheduler.as_bulk_resolve(ips, threads=len(ips))
  File "/usr/lib/python2.6/site-packages/pscheduler/psas.py", line 84, in as_bulk_resolve
    chunksize=1):
  File "/usr/lib64/python2.6/multiprocessing/pool.py", line 520, in next
    raise value
dns.name.EmptyLabel"
```

Looks like we're not catching the exception listed above.

**Comment by mfeit-internet2** [comment]
This is apparently caused by poorly-configured DNS zones:  http://stackoverflow.com/questions/8470141/blank-name-field-in-dns-zone-file-record
