### ISSUE TITLE
pscheduler-test-trace participants returns "UnicodeError: label empty or too long"

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#420]
The following was reported by Jeff Hagley at internet2:

Begin forwarded message:

From: <user@localhost.internet2.edu>
Subject: [abrt] pscheduler-test-trace: pool.py:655:next:UnicodeError: label empty or too long
Date: April 26, 2017 at 7:53:36 AM EDT
To: <root@localhost.internet2.edu>

reason:         pool.py:655:next:UnicodeError: label empty or too long
cmdline:        /usr/bin/python /usr/libexec/pscheduler/commands/../classes/test/trace/participants
executable:     /usr/libexec/pscheduler/classes/test/trace/participants
package:        pscheduler-test-trace-1.0-1.el7.centos
component:      pscheduler-test-trace
pid:            30344
hostname:       perf0.aa.internet2.edu
count:          20
abrt_version:   2.1.11
analyzer:       Python
architecture:   x86_64
duphash:        12aee20e02e8373606da0315660d735822c3d8c3
event_log:      
kernel:         3.10.0-514.16.1.el7.x86_64
last_occurrence: 1493207616
os_release:     CentOS Linux release 7.3.1611 (Core)
pkg_arch:       noarch
pkg_epoch:      0
pkg_fingerprint: 868D DF2C 9D7B 9686
pkg_name:       pscheduler-test-trace
pkg_release:    1.el7.centos
pkg_vendor:     (none)
pkg_version:    1.0
runlevel:       N 3
time:           Tue 25 Apr 2017 05:50:34 PM UTC
type:           Python
uid:            1000
username:       pscheduler
uuid:           12aee20e02e8373606da0315660d735822c3d8c3

backtrace:
:pool.py:655:next:UnicodeError: label empty or too long
:
:Traceback (most recent call last):
:  File "/usr/libexec/pscheduler/commands/../classes/test/trace/participants", line 42, in <module>
:    has = pscheduler.api_has_services([source, destination], timeout=3)
:  File "/usr/lib/python2.7/site-packages/pscheduler/api.py", line 280, in api_has_services
:    for host, service, state in pool.imap(check_one, args, chunksize=1):
:  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
:    raise value
:UnicodeError: label empty or too long
:
:Local variables in innermost frame:
:item: (False, UnicodeError('label empty or too long',))
:timeout: None
:success: False
:value: UnicodeError('label empty or too long',)
:self: <multiprocessing.pool.IMapIterator object at 0x1f53150>
dso_list:
:python-pscheduler-1.3-1.el7.centos.noarch
:python-libs-2.7.5-48.el7.x86_64
environ:
:LANG=C
:NOTIFY_SOCKET=/run/systemd/notify
:SHLVL=0
:PSCHEDULER_LOG_STATE=(dp0
:S'is_quiet'
:p1
:I00
:sS'facility'
:p2
:I20
:sS'last_level'
:p3
:I20
:sS'forced_debug'
:p4
:I00
:s.
:PWD=/home/pscheduler
:HOME=/home/pscheduler
:PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
machineid:
:systemd=876d048152464a1287ce71ffabaa5ca0
:sosreport_uploader-dmidecode=d093584752ff02802858941132f2e098addcb6f484675cf7dae34a34f7f37701
os_info:
:NAME="CentOS Linux"
:VERSION="7 (Core)"
:ID="centos"
:ID_LIKE="rhel fedora"
:VERSION_ID="7"
:PRETTY_NAME="CentOS Linux 7 (Core)"
:ANSI_COLOR="0;31"
:CPE_NAME="cpe:/o:centos:centos:7"
:HOME_URL="https://www.centos.org/"
:BUG_REPORT_URL="https://bugs.centos.org/"
:
:CENTOS_MANTISBT_PROJECT="CentOS-7"
:CENTOS_MANTISBT_PROJECT_VERSION="7"
:REDHAT_SUPPORT_PRODUCT="centos"
:REDHAT_SUPPORT_PRODUCT_VERSION="7"
:

**Comment by arlake228** [comment]
Looks like this was caused by a bad hostname perf0.sf..internet2.edu (extra .). Leaving this open so we can look at throwing a better error message.
