### ISSUE TITLE
pscheduler-scheduler needs restart after a few days

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#423]
On pretty much all the ESnet hosts as far as I can tell, after a few days pscheduler-server seems to stop scheduling new runs and needs a restart. I have been waking up most mornings to 1 or 2 in this state, and it always appears to be different ones. As soon as you do the restart it starts scheduling new runs. So far I have been unable to find any errors in pscheduler.log, so i don't have much more information. I think a few people on the list have seen this as well and they've either rebooted or restarted the service and things have come back.

**Comment by vvidic** [comment]
On Fri, Apr 28, 2017 at 05:21:28AM -0700, Andrew R. Lake wrote:
> On pretty much all the ESnet hosts as far as I can tell, after a few
> days pscheduler-server seems to stop scheduling new runs and needs a
> restart. I have been waking up most mornings to 1 or 2 in this state,
> and it always appears to be different ones. As soon as you do the
> restart it starts scheduling new runs. So far I have been unable to
> find any errors in pscheduler.log, so i don't have much more
> information. I think a few people on the list have seen this as well
> and they've either rebooted or restarted the service and things have
> come back. 

Does the strace of the process or postgresql query list say what it
might be doing when stuck like this?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
Andy observed that the program was stuck doing a read.  Call stack looks like this:

```
#0  0x00007fb52a83182d in read () from /lib64/libpthread.so.0
#1  0x00007fb5233e2e01 in ?? () from /usr/lib64/libcrypto.so.10
#2  0x00007fb5233e1159 in BIO_read () from /usr/lib64/libcrypto.so.10
#3  0x00007fb52371529f in ssl3_read_n () from /usr/lib64/libssl.so.10
#4  0x00007fb5237159dd in ssl3_read_bytes () from /usr/lib64/libssl.so.10
#5  0x00007fb523711260 in ?? () from /usr/lib64/libssl.so.10
#6  0x00007fb523958c64 in ?? () from /usr/lib64/python2.6/lib-dynload/_ssl.so
#7  0x00007fb52ab159d4 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#8  0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#9  0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#10 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#11 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#12 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#13 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#14 0x00007fb52ab16b7f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#15 0x00007fb52ab16b7f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#16 0x00007fb52ab16b7f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#17 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#18 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#19 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#20 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#21 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#22 0x00007fb52aaaad9d in ?? () from /usr/lib64/libpython2.6.so.1.0
#23 0x00007fb52aa83c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#24 0x00007fb52ab14460 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#25 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#26 0x00007fb52aaaad9d in ?? () from /usr/lib64/libpython2.6.so.1.0
#27 0x00007fb52aa83c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#28 0x00007fb52ab14460 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#29 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#30 0x00007fb52aaaad9d in ?? () from /usr/lib64/libpython2.6.so.1.0
#31 0x00007fb52aa83c63 in PyObject_Call () from /usr/lib64/libpython2.6.so.1.0
#32 0x00007fb52ab14460 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#33 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#34 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#35 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#36 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#37 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#38 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#39 0x00007fb52ab16b7f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#40 0x00007fb52ab16b7f in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#41 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#42 0x00007fb52ab15a94 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.6.so.1.0
#43 0x00007fb52ab17647 in PyEval_EvalCodeEx () from /usr/lib64/libpython2.6.so.1.0
#44 0x00007fb52ab17722 in PyEval_EvalCode () from /usr/lib64/libpython2.6.so.1.0
#45 0x00007fb52ab31b9c in ?? () from /usr/lib64/libpython2.6.so.1.0
#46 0x00007fb52ab31c70 in PyRun_FileExFlags () from /usr/lib64/libpython2.6.so.1.0
#47 0x00007fb52ab3315c in PyRun_SimpleFileExFlags () from /usr/lib64/libpython2.6.so.1.0
#48 0x00007fb52ab3f892 in Py_Main () from /usr/lib64/libpython2.6.so.1.0
#49 0x00007fb529e22d1d in __libc_start_main () from /lib64/libc.so.6
#50 0x0000000000400649 in _start ()
```

This is likely a call to `url_*` with no timeout where there should be one.

**Comment by mfeit-internet2** [comment]
Andy's commits plus #357 should resolve this fully.  Closing.
