### ISSUE TITLE
Hostnames with only AAAA cause error in iperf3 tool 

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#429]
Giving an iperf3 test a hostname with only a AAAA record leads to the following error:

`['Traceback (most recent call last):', '  File "/usr/libexec/pscheduler/commands/../classes/tool/iperf3/run", line 364, in <module>\n    results = run_client()', '  File "/usr/libexec/pscheduler/commands/../classes/tool/iperf3/run", line 217, in run_client\n    affinity = pscheduler.source_affinity(destination)', '  File "/usr/lib/python2.6/site-packages/pscheduler/interface.py", line 20, in source_affinity\n    (address, intf) = source_interface(addr)', '  File "/usr/lib/python2.6/site-packages/pscheduler/interface.py", line 36, in source_interface\n    s.connect((addr,port))', '  File "<string>", line 1, in connect', 'gaierror: [Errno -2] Name or service not known']`

Looks like when determining the CPU affinity and looking up the interface it assumes AF_INET.

**Comment by arlake228** [comment]
Looks to be fixed after last few commits
