### ISSUE TITLE
Using raw IPv6 address for source causes command-line client failure

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#430]
If a raw IPv6 address is the source (really the lead) of a test seems to cause an error in the command-line client. Looks like another URL issue potentially. Multiple layers to this issue as it seems to trigger bug that masks real issue. The error you get is as follows:

```
Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/task", line 639, in <module>
    json=True)
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 130, in url_get
    __raise_urlexception(status, text, request)
UnboundLocalError: local variable 'request' referenced before assignment
```

If i add some quick fixes to get rid of that error, the root cause is something `Error: Failed to parse: 2001:400:301:1150::3`.

**Comment by arlake228** [comment]
Closing can't recreate after latest batch of fixes. I think some of the other fixes may have corrected this.
