### ISSUE TITLE
pscheduler iperf3 plugin 'InternalError'

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#469]
I'm seeing this regularly in the logs on nettest.lbl.gov:

```
May 30 17:04:11 nettest pscheduler-api ERROR    Exception: InternalError: Unable to get merged result on {"test": {"spec": {"dest": "nettest.lbl.gov", "schema": 1, "source": "167.191.118.97", "duration": "PT20S", "parallel": 1, "ip-version": 4}, "type": "throughput"}, "results": [null, {"error": "iperf3 returned an error: ", "succeeded": false}]}: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/iperf3/merged-results", line 43, in <module>
    final_results['diags'] = final_diag
TypeError: 'NoneType' object does not support item assignment


Traceback (most recent call last):
  File "./pschedulerapiserver/runs.py", line 536, in tasks_uuid_runs_run
  File "./pschedulerapiserver/dbcursor.py", line 112, in dbcursor_query
InternalError: Unable to get merged result on {"test": {"spec": {"dest": "nettest.lbl.gov", "schema": 1, "source": "167.191.118.97", "duration": "PT20S", "parallel": 1, "ip-version": 4}, "type": "throughput"}, "results": [null, {"error": "iperf3 returned an error: ", "succeeded": false}]}: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/iperf3/merged-results", line 43, in <module>
    final_results['diags'] = final_diag
TypeError: 'NoneType' object does not support item assignment
```

**Comment by daldoyle** [comment]
Should be fixed by this:
https://github.com/perfsonar/pscheduler/commit/3584d1e68d2d95f85d674fe9535705db64142c20
