### ISSUE TITLE
pscheduler-tool-pysnmp: fails to get value

### ISSUE THREAD

**Issue by vvidic** [perfsonar/pscheduler#541]
SNMP server is running:

```
$ snmpget -v 2c -c public localhost 1.3.6.1.2.1.1.1.0
iso.3.6.1.2.1.1.1.0 = STRING: "Linux jessie-amd64 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64"
```

But tool fails to get this value:

```
$ pscheduler task --tool pysnmp snmpget  --version 2c --community public --oid 1.3.6.1.2.1.1.1.0 --dest localhost 
Submitting task...
Task URL:
https://jessie-amd64/pscheduler/tasks/1d124aa5-c2f5-4c63-9284-68082e5c384b
Running with tool 'pysnmp'
Fetching first run...

Next scheduled run:
https://jessie-amd64/pscheduler/tasks/1d124aa5-c2f5-4c63-9284-68082e5c384b/runs/3bea0f68-8438-40bf-adb1-1cfe9e195f90
Starts 2017-08-23T16:13:09+02:00 (~7 seconds)
Ends   2017-08-23T16:13:20+02:00 (~10 seconds)
Waiting for result...
Run failed: Traceback (most recent call last):
  File "/usr/lib/pscheduler/commands/../classes/tool/pysnmp/run", line 164, in <module>
    errorIndication, errorStatus, errorIndex, varBinds = next(g)
  File "/usr/lib/python2.7/dist-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 107, in getCmd
    lookupMib=options.get('lookupMib', True)))
  File "/usr/lib/python2.7/dist-packages/pysnmp/hlapi/asyncore/cmdgen.py", line 122, in getCmd
    addrName, paramsName = lcd.configure(snmpEngine, authData, transportTarget)
  File "/usr/lib/python2.7/dist-packages/pysnmp/hlapi/lcd.py", line 44, in configure
    authData.securityName
  File "/usr/lib/python2.7/dist-packages/pysnmp/entity/config.py", line 71, in addV1System
    ((snmpCommunityEntry.name + (8,) + tblIdx, 'destroy'),)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/instrum.py", line 250, in writeVars
    return self.flipFlopFsm(self.fsmWriteVar, vars, acInfo)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/instrum.py", line 218, in flipFlopFsm
    rval = f(tuple(name), val, idx, acInfo)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 470, in writeTest
    node.writeTest(name, val, idx, acInfo)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 1117, in writeTest
    self.__delegate('Test', name, val, idx, acInfo)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 1088, in __delegate
    name, val, idx, acInfo
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 886, in writeTest
    self.createTest(name, val, idx, acInfo)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 793, in createTest
    self.__createdInstances[name].createTest(name, val, idx, acInfo)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 699, in createTest
    self.__newSyntax = self.setValue(val, name, idx)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 591, in setValue
    return self.syntax.setValue(value)
  File "/usr/lib/python2.7/dist-packages/pysnmp/smi/mibs/SNMPv2-TC.py", line 289, in setValue
    (value.hasValue() and value or self.stNotExists,
AttributeError: RowStatus instance has no attribute 'hasValue'
```

**Comment by mfeit-internet2** [comment]
Looks like it might be a falling-off-the-end error in the run method, line 160.
