### ISSUE TITLE
File Getting Left Open

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#548]
Marian Babik observed this:

```
Sep 11 15:25:36 perfsonar-lt safe_run/ticker ERROR    Restarting
Sep 11 15:25:36 perfsonar-lt safe_run/ticker ERROR    Program threw an exception after 0:00:00.002590
Sep 11 15:25:36 perfsonar-lt safe_run/ticker ERROR    Exception: IOError: [Errno 24] Too many open files: '/etc/pscheduler/database/database-dsn'#012Traceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41,
in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/ticker", line 153, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/ticker", line 123, in main_program#012    db = pscheduler.pg_
connection(dsn)#012  File "/usr/lib/python2.6/site-packages/pscheduler/db.py", line 28, in pg_connection#012    dsn = string_from_file(dsn)#012  File "/usr/lib/python2.6/site-packages/pscheduler/filestring.py", line 24, in string_from_file#012    with open(pat
h, 'r') as content:#012IOError: [Errno 24] Too many open files: '/etc/pscheduler/database/database-dsn'
Sep 11 15:25:36 perfsonar-lt safe_run/ticker ERROR    Waiting 60.0 seconds before restarting
```

Looks like the problem is too many Unix-domain sockets being open, probably as connections to PostgreSQL.

A better way to solve this would be for `safe_run` to re-exec the program and find a way to pickle and pass its state data through the environment like the logger does.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Improved safety of automatic program restarts.
