### ISSUE TITLE
throughput: Unable to retrieve formatted result

### ISSUE THREAD

**Issue by vvidic** [perfsonar/pscheduler#549]
```
$ pscheduler task throughput --bandwidth 50000000 --duration PT10S --source perfsonar-dev5.grnoc.iu.edu --ip-version 4 --dest pstest.geant.carnet.hr --window-size 1024000 --parallel 1 --udp
Submitting task...
Task URL:
https://pstest.geant.carnet.hr/pscheduler/tasks/a2128780-28d6-4c31-bca8-458e74c2bd69
Running with tool 'bwctliperf3'
Fetching first run...

Next scheduled run:
https://pstest.geant.carnet.hr/pscheduler/tasks/a2128780-28d6-4c31-bca8-458e74c2bd69/runs/68e5b051-5a2a-4d47-ac98-4d4b018fa868
Starts 2017-09-20T16:03:24+02:00 (~171 seconds)
Ends   2017-09-20T16:04:35+02:00 (~70 seconds)
Waiting for result...
Unable to retrieve formatted result: Failed to format result: Traceback (most recent call last):
  File "/usr/lib/pscheduler/commands/../classes/test/throughput/result-format", line 45, in <module>
    intervals.sort(key=lambda x: (not x["summary"].get("omitted"), x["summary"]["start"]))
  File "/usr/lib/pscheduler/commands/../classes/test/throughput/result-format", line 45, in <lambda>
    intervals.sort(key=lambda x: (not x["summary"].get("omitted"), x["summary"]["start"]))
KeyError: 'start'
```

**Comment by mfeit-internet2** [comment]
This is/was a problem in code that has been removed in 4.2.0.  Closing.
