### ISSUE TITLE
InternalError: Unable to get merged result on....: Process took too long to run

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#559]
Hello Mark,

There is a report of an issue with pScheduler going into a blocked state, where it is not possible to serve and manage tasks as reported below. The version in question is pS toolkit 4.0.1..
The mitigation is to restart the server. 
Unclear is:
- if service restart would solve the problem, the same way as with host restart
- Casey stated, that he is now using pS 4.0.2 on some of these hosts. He will report back how these new updates will behave in time. 

The log events observed are:
```
From: Casey Russell [mailto:crussell@kanren.net] 
Sent: Dienstag, 17. Oktober 2017 15:17
To: Garnizov, Ivan (RRZE)
Cc: perfsonar-user@internet2.edu
Subject: Re: [perfsonar-user] meshconfig-agent-tasks not scheduling tasks regularly
```
```
Oct 16 16:00:13 ps-washburn-bw runner INFO     7239354: Run failed 2: Process took too long to run.
Oct 16 16:00:14 ps-washburn-bw pscheduler-api ERROR    Exception: InternalError: Unable to get merged result on {"test": {"spec": {"dest": "ps-wsu-bw.perfsonar.kanren.net", "schema": 1, "source": "ps-washburn-bw.perfsonar.kanren.net", "ip-version": 4}, "type": "trace"}, "results": [null]}: Process took too long to run.#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/runs.py", line 545, in tasks_uuid_runs_run#012  File "./pschedulerapiserver/dbcursor.py", line 112, in dbcursor_query#012InternalError: Unable to get merged result on {"test": {"spec": {"dest": "ps-wsu-bw.perfsonar.kanren.net", "schema": 1, "source": "ps-washburn-bw.perfsonar.kanren.net", "ip-version": 4}, "type": "trace"}, "results": [null]}: Process took too long to run.
Oct 16 16:00:14 ps-washburn-bw runner WARNING  7239157: Unable to update run https://ps-washburn-bw.perfsonar.kanren.net/pscheduler/tasks/28d2b84d-4d84-4d3e-a901-1a2d63425223/runs/ea10f21a-ba12-453b-b1c2-22988698c04d: 500 Unable to get merged result on {"test": {"spec": {"dest": "ps-wsu-bw.perfsonar.kanren.net", "schema": 1, "source": "ps-washburn-bw.perfsonar.kanren.net", "ip-version": 4}, "type": "trace"}, "results": [null]}: Process took too long to run.#012
Oct 16 16:00:41 ps-washburn-bw runner INFO     7190345: Run failed 2: Process took too long to run.
Oct 16 16:00:51 ps-washburn-bw scheduler INFO     24433: Posting non-starting run at 2017-10-17T08:38:23-05:00 for task eac7ccd1-386f-4fff-9e25-70ca2a124824: Failed to post/put runs to all participants: Failed to validate limit: Process took too long to run.
Oct 16 16:01:23 ps-washburn-bw runner INFO     7239232: Run failed 2: Process took too long to run.
Oct 16 16:01:24 ps-washburn-bw runner INFO     7204637: Run failed 2: Process took too long to run.
```

**Comment by arlake228** [comment]
I'm closing this since this is almost definitely an overloaded host. We saw this numerous times before the archiving performance fixes added in 4.0.2. Casey indicated these were lower-powered hosts in his email and at least so far 4.0.2 seems to help after he upgraded. We can re-open or create a new issue if he finds anything deeper, but this very much looks like a known performance issue.
