### ISSUE TITLE
Runner loses connection to PostgreSQL

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#581]
Periodically on my development VMs (and _only_ there), I'll start the system up and have the runner lose its connection to the database because the database thinks it send an invalid message.

This may be a thread safety problem.

Edit:  Ryan has seen this on his VirtualBox VMs as well.

-----
Runner says:
```
pscheduler.log:Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    Program threw an exception after 21:13:24.952918
pscheduler.log:Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    Exception: OperationalError: server closed the connection unexpectedly
pscheduler.log:Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    #011This probably means the server terminated abnormally
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    #011before or while processing the request.
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    Traceback (most recent call last):
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR      File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 72, in safe_run
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR        function()
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR      File "/usr/libexec/pscheduler/daemons/runner", line 934, in <lambda>
log:Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR        pscheduler.safe_run(lambda: main_program())
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR      File "/usr/libexec/pscheduler/daemons/runner", line 843, in main_program
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR        """, [refresh]);
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    OperationalError: server closed the connection unexpectedly
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    #011This probably means the server terminated abnormally
Feb 27 10:53:01 dev7 journal: safe_run/runner ERROR    #011before or while processing the request.
```
-----
Database says:
```
< 2018-02-27 10:53:01.018 EST >FATAL:  invalid frontend message type 60
```

**Comment by mfeit-internet2** [comment]
Szymon saw this on a small node, so it's not just a VM problem anymore.

**Comment by szymontrocha** [comment]
I just saw this issue also in other small nodes so it was not just a single box.

**Comment by mfeit-internet2** [comment]
More insight:  Discovered that this happens very consistently right after an install but goes away after a restart and behaves well afterward.  Therefore, it might not be the code but something we're doing in the spec that's the root cause.

**Comment by mfeit-internet2** [comment]
Turned out to be that FDs were not getting closed by `safe_run` before a re-exec, and that was causing problems.  Calling this one done.

**Comment by mfeit-internet2** [comment]
Re-opening temporarily to reconstitute a branch for merging into the 4.1.1 release.
