### ISSUE TITLE
Troubleshooter doesn't play nice with IPv6

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#626]
To wit:
```
% pscheduler troubleshoot 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14
Performing basic troubleshooting of localhost and 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14.

localhost:

  Checking path MTU... 65520+
  Checking for pScheduler... OK.
  Checking clock... OK.
  Idle test.... 13 seconds.... Checking archiving... OK.

2610:e0:a000:ffff:ee0d:9aff:fec8:4a14:

  Checking path MTU... Unsafe or unknown: Error: tracepath: 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14: Address family for hostname not supported
  Checking for pScheduler... OK.
  Checking clock... Unsynchronized  (See check against 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14)
  Idle test.... 4 seconds.... Checking archiving... OK.

localhost and 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14:

  Checking path MTU... Unsafe or unknown: Error: tracepath: 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14: Address family for hostname not supported
  Checking timekeeping... OK.
  Simple stream test.... 13 seconds.... Failed.
Task failed to run properly.

2018-05-24T16:54:18-04:00 on localhost and 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14 with simplestreamer:

simplestream --dest 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14

Run failed.

Limit system diagnostics:
  Hints:
    requester: ::1
    server: ::1
  Identified as everybody, local-interfaces
  Classified as default, friendlies
  Application: Hosts we trust to do everything
    Group 1: Limit 'always' passed
    Group 1: Want all, 1/1 passed, 0/1 failed: PASS
    Application PASSES
  Application: Defaults applied to non-friendly hosts
    Group 1: Limit 'innocuous-tests' passed
    Group 1: Limit 'throughput-default-time' failed: Test is not 'throughput'
    Group 1: Limit 'idleex-default' failed: Test is not 'idleex'
    Group 1: Want any, 1/3 passed, 2/3 failed: PASS
    Application PASSES
  Proposal meets limits


Diagnostics from localhost:
    Try 1 failed: [Errno -9] Address family for hostname not supported
    Try 2 failed: [Errno -9] Address family for hostname not supported
    Try 3 failed: [Errno -9] Address family for hostname not supported
    Try 4 failed: [Errno -9] Address family for hostname not supported
    Try 5 failed: [Errno -9] Address family for hostname not supported
    Try 6 failed: [Errno -9] Address family for hostname not supported
    Try 7 failed: [Errno -9] Address family for hostname not supported
    Try 8 failed: [Errno -9] Address family for hostname not supported
    Try 9 failed: [Errno -9] Address family for hostname not supported
    Try 10 failed: [Errno -9] Address family for hostname not supported

Error from localhost:
    Failed to connect: [Errno -9] Address family for hostname not supported

Diagnostics from 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14:
    Nothing to see at the receiving end.

Error from 2610:e0:a000:ffff:ee0d:9aff:fec8:4a14:
    Receiver exception: [Errno -9] Address family for hostname not supported Traceback (most recent call last):
      File "/usr/libexec/pscheduler/commands/../classes/tool/simplestreamer/run", line 169, in <module>
        sock.bind(server_address)
      File "/usr/lib64/python2.7/socket.py", line 224, in meth
        return getattr(self._sock,name)(*args)
    gaierror: [Errno -9] Address family for hostname not supported
```

Two things need fixing:

 - [ ] Troubleshooter needs to invoke `tracepath6` for IPv6 addresses
 - [ ] Should have a switch to force IPv6
 - [ ] Simplestream needs a way to do IPv6 and/or be told to do it.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added IPv6 support to the `simplestream` test 
Added IPv6 support to the `simplestreamer` tool.
Added IPv6 support to the troubleshooter.
