### ISSUE TITLE
NoneType not assignable error

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#636]
This is probably happening in the server.  Need to see why.  If the server isn't logging the exception somewhere, it should be.

```
% psi
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/b39b8273-1179-4749-8715-c5f7b8aef907
Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/task", line 668, in <module>
    json=True)
  File "/usr/lib/python2.7/site-packages/pscheduler/psurl.py", line 150, in url_get
    __raise_urlexception(status, text, request)
  File "/usr/lib/python2.7/site-packages/pscheduler/psurl.py", line 86, in __raise_urlexception
    raise URLException(text)
pscheduler.psurl.URLException: 'NoneType' object does not support item assignment
```

From the logs:

```
Jun 15 10:17:07 dev7 journal: pscheduler-api DEBUG    Debug started
Jun 15 10:17:07 dev7 journal: pscheduler-api DEBUG    REQUEST: GET https://localhost/pscheduler/tasks/cb71566a-6ceb-42c9-bdad-8b9822
337323?pretty
Jun 15 10:17:07 dev7 journal: pscheduler-api DEBUG    QUERY: SELECT json_detail, uuid FROM task WHERE task.uuid = %s, [u'cb71566a-6c
eb-42c9-bdad-8b9822337323']
Jun 15 10:17:07 dev7 journal: pscheduler-api DEBUG    QUERY returned 1 rows
Jun 15 10:17:07 dev7 journal: pscheduler-api DEBUG    Response 500: 'NoneType' object does not support item assignment
Jun 15 10:17:33 dev7 journal: pscheduler-api DEBUG    REQUEST: GET https://localhost/pscheduler/tasks/cb71566a-6ceb-42c9-bdad-8b9822
337323
Jun 15 10:17:33 dev7 journal: pscheduler-api DEBUG    QUERY: SELECT json_detail, uuid FROM task WHERE task.uuid = %s, [u'cb71566a-6c
eb-42c9-bdad-8b9822337323']
Jun 15 10:17:33 dev7 journal: pscheduler-api DEBUG    QUERY returned 1 rows
Jun 15 10:17:33 dev7 journal: pscheduler-api DEBUG    Response 500: 'NoneType' object does not support item assignment
```

**Comment by mfeit-internet2** [comment]
This is fixed; closing.
