### ISSUE TITLE
pscheduler exception on failed runs

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#702]
Hi Mark,
Please note the pscheduler fails with the run, but then for whatever reason applies " [ result_full, succeeded, run, task ]"
also check the **** mark

installed is:
python-pscheduler/perfsonar-unstable,now 1.3.4+20181011201927-1 all [installed,automatic]

```
Oct 18 10:38:35 t2-psdev runner INFO     380754: With iperf3: throughput --bandwidth 50000000 --duration PT10S --source t2-psdev.rrze.uni-erlangen.de --ip-version 4 --dest perfsonar-dev5.grnoc.iu.edu --window-size 1024000 --source-node t2-psdev.rrze.uni-erlangen.de --dest-node perfsonar-dev5.grnoc.iu.edu --udp
Oct 18 10:38:35 t2-psdev runner INFO     380754: Run failed 1: iperf3 requires exactly 2 participants, got 1
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR    Exception: InternalError: Unable to get merged result on {"test": {"spec": {"udp": true, "dest": "perfsonar-dev5.grnoc.iu.edu", "schema": 1, "source": "t2-psdev.rrze.uni-erlangen.de", "duration": "PT10S", "bandwidth": 50000000, "dest-node": "perfsonar-dev5.grnoc.iu.edu", "ip-version": 4, "source-node": "t2-psdev.rrze.uni-erlangen.de", "window-size": 1024000}, "type": "throughput"}, "results": [null]}: Expected 2 results in merged-results, got 1
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR    Traceback (most recent call last):
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR        rv = self.dispatch_request()
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR        return self.view_functions[rule.endpoint](**req.view_args)
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR      File "/usr/share/pscheduler/api-server/pschedulerapiserver/runs.py", line 511, in tasks_uuid_runs_run
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR        [ result_full, succeeded, run, task ])
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR      File "/usr/share/pscheduler/api-server/pschedulerapiserver/dbcursor.py", line 112, in dbcursor_query
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR        raise ex

****
Oct 18 10:38:40 t2-psdev pscheduler-api ERROR    InternalError: Unable to get merged result on {"test": {"spec": {"udp": true, "dest": "perfsonar-dev5.grnoc.iu.edu", "schema": 1, "source": "t2-psdev.rrze.uni-erlangen.de", "duration": "PT10S", "bandwidth": 50000000, "dest-node": "perfsonar-dev5.grnoc.iu.edu", "ip-version": 4, "source-node": "t2-psdev.rrze.uni-erlangen.de", "window-size": 1024000}, "type": "throughput"}, "results": [null]}: Expected 2 results in merged-results, got 1

Oct 18 10:38:40 t2-psdev runner WARNING  380754: Unable to update run https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/9c038089-1d0c-4960-9f4a-db96b5f5994c/runs/c0ecb349-699e-4444-8f72-dc95b1107bf3: 500 Internal problem; see system logs.

```

**Comment by mfeit-internet2** [comment]
I moved the merging of results into the runner so the database doesn't have to contend with it.  That solves half the problem and gets the error into the results so end users don't have to fish through the logs to find it.

The error itself is likely because of some weird behavior in the BWCTL backward compatibility hack where network conditions made it draw the conclusion that there was only one participant instead of two.  That will go away when the hack does.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Improved the way certain failures in post-run processing are handled.
