### ISSUE TITLE
Scheduler throws exception

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#71]
The scheduler has been seen throwing this exception:

```
Aug  1 14:13:15 dev9 safe_run/scheduler ERROR    Exception: MissingSchema: Invalid URL u"global name 'cursor' is not defined\n": No schema supplied. Perhaps you meant http://global name 'cursor' is not defined?
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run
    function()
  File "/usr/libexec/pscheduler/daemons/scheduler", line 127, in <lambda>
    pscheduler.safe_run(lambda: main_program())
  File "/usr/libexec/pscheduler/daemons/scheduler", line 119, in main_program
    pscheduler.run_post(url, trynext, log)
  File "/usr/lib/python2.6/site-packages/pscheduler/postrun.py", line 226, in run_post
    pscheduler.url_delete_list(runs_posted)
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 144, in url_delete_list
    return [ url_delete(url, throw=False) for url in urls ]
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 128, in url_delete
    request = requests.delete(url, verify=verify_keys)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 146, in delete
    return request('delete', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.6/site-packages/requests/models.py", line 361, in prepare_url
    "Perhaps you meant http://{0}?".format(url))

MissingSchema: Invalid URL u"global name 'cursor' is not defined\n": No schema supplied. Perhaps you meant http://global name 'cursor' is not defined
```
And a similar one:
```
MissingSchema: Invalid URL u"global name 'psycopg2' is not defined\n": No schema supplied. Perhaps you meant http://global name 'psycopg2' is not defined
```

These are happening during a call to delete a URL, so it's possible that the URL `post_run` is getting back is wrong because of an error.

**Comment by mfeit-internet2** [comment]
This was the file on the date this bug was filed:  https://github.com/perfsonar/pscheduler/blob/d93e6b3961a0febcac354ee9b7091c4090a3096e/pscheduler-server/pscheduler-server/scheduler

Not seeing this as a problem anymore; closing.
