### ISSUE TITLE
Occasional Empty Queries

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#75]
Periodically seeing this while scheduling a string of the same task repeatedly, while converting the arg list to JSON (turned on throwing for more diagnostics):
```
Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/task", line 380, in <module>
    throw=True
  File "/usr/lib/python2.6/site-packages/pscheduler/psurl.py", line 57, in url_get
    + ": " + text)
pscheduler.psurl.URLException: https://127.0.0.1/pscheduler/tests/idle/spec: 500: can't execute an empty query
```

**Comment by mfeit-internet2** [comment]
Can no longer duplicate the problem.
