### ISSUE TITLE
Need to provide an updated python2-pyasn1-modules package

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#794]
@opoplawski commented on [Wed Mar 20 2019](https://github.com/perfsonar/project/issues/1222)

The perfsonar provided python2-pyasn1 package breaks pyasn1_modules:
```
# python
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyasn1_modules import rfc2315, rfc2459
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyasn1_modules/rfc2315.py", line 67, in <module>
    class DigestedData(univ.Sequence):
  File "/usr/lib/python2.7/site-packages/pyasn1_modules/rfc2315.py", line 72, in DigestedData
    namedtype.NamedType('digest', Digest)
  File "/usr/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 115, in __init__
    self.__ambiguousTypes = 'terminal' not in kwargs and self.__computeAmbiguousTypes() or {}
  File "/usr/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 232, in __computeAmbiguousTypes
    ambigiousTypes[idx] = NamedTypes(*partialAmbigiousTypes, **dict(terminal=True))
  File "/usr/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 114, in __init__
    self.__tagToPosMap = self.__computeTagToPosMap()
  File "/usr/lib/python2.7/site-packages/pyasn1/type/namedtype.py", line 205, in __computeTagToPosMap
    for _tagSet in tagMap.presentTypes:
AttributeError: 'property' object has no attribute 'presentTypes'
>>>
```
```
Installed Packages
python2-pyasn1.x86_64                             0.3.7-1.el7.centos                     @perfSONAR
python2-pyasn1-modules.noarch                     0.1.9-7.el7                            @base
Available Packages
python2-pyasn1.noarch                             0.1.9-7.el7                            base
```
Please provide an updated python2-pyasn1-modules package to match.  This currently breaks a lot of IPA related stuff.

**Comment by mfeit-internet2** [comment]
This has been done and will be released in 4.2.0.
