### ISSUE TITLE
Exception while posting task

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#798]
Marian observed the following on two of his systems which are freshly-installed 4.1.6:

```
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR    Exception: TypeError: 'str' object does not support item assignment
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR    Traceback (most recent call last):
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR      File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR        rv = self.dispatch_request()
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR      File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR        return self.view_functions[rule.endpoint](**req.view_args)
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR      File "./pschedulerapiserver/tasks.py", line 615, in tasks_uuid
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR      File "./pschedulerapiserver/tasks.py", line 140, in __tasks_get_filtered
Mar 22 12:36:56 p07383215q66997 journal: pscheduler-api ERROR    TypeError: 'str' object does not support item assignment
```

[The line where this occurs](https://github.com/perfsonar/pscheduler/blob/17defca9761dee93deea7a3a1d9f7ebd39602a14/pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/tasks.py#L140) hasn't been changed in over a year.

**Comment by mfeit-internet2** [comment]
Can't replicate this on a fresh VM.  Will be asking Marian if I can get on the system to see what's going on.

**Comment by mfeit-internet2** [comment]
Fetching `/tasks/<uuid>` doesn't work.  The call to `__tasks_get_filtered()` queries the database, which returns a row containing string and a UUID instead of JSON and a UUID.  This was a force-added logging, not an error:

```
Mar 22 23:06:29 p07383215f88745 journal: pscheduler-api ERROR    ROW ('{"test": {"spec": {"schema": 1, "duration": "PT5S"}, "type": 
"idle"}, "tool": "snooze", "detail": {"cli": ["--duration", "PT5S"], "post": "P0D", "runs": 0, "slip": "PT5M", "added": "2019-03-22T
23:06:28+01", "diags": "Hints:\\n  requester: 127.0.0.1\\n  server: 127.0.0.1\\nIdentified as everybody, local-interfaces\\nClassifi
ed as default, friendlies\\nRewriter made changes:\\n  Bumped duration to 5-second minimum\\nApplication: Hosts we trust to do every
thing\\n  Group 1: Limit \'always\' passed\\n  Group 1: Want all, 1/1 passed, 0/1 failed: PASS\\n  Application PASSES\\nApplication:
 Defaults applied to non-friendly hosts\\n  Group 1: Limit \'innocuous-tests\' passed\\n  Group 1: Limit \'throughput-default-time\'
 failed: Test is not \'throughput\'\\n  Group 1: Limit \'idleex-default\' failed: Test is not \'idleex\'\\n  Group 1: Want any, 1/3 
passed, 2/3 failed: PASS\\n  Application PASSES\\nProposal meets limits", "start": null, "anytime": true, "enabled": true, "duration
": "PT5S", "exclusive": false, "participant": 0, "multi-result": false, "participants": ["localhost"], "runs-started": 0, "spec-limi
ts-passed": []}, "schema": 1, "schedule": {"slip": "PT5M"}}', '3a67bdff-0b06-4bec-a643-dc73c71b48ad')
```
The columns in the database look as expected.

Checked on Psycopg2.  

Our systems seem to have 2.6.1; Marian's has 2.5.1, which lacks the support for `JSONB` introduced in 2.5.4.

Marin's system looks like it's getting pretty much everything from sources at CERN, which do not include anything current enough.  Ours installs from PGDG.  CERN needs more-current repositories.

Action item for us:  Make sure the version requirement for python-psycopg2 is >= 2.6.1.
