### ISSUE TITLE
API pscheduler debug failures

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#807]
`sudo pscheduler debug on api` leads to errors:
I have seen the same on a Ubuntu 16, pS 4.1.6 Testpoint

```
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR    Exception: IOError: [Errno 2] No such file or directory: '/run/pscheduler-server/pscheduler-api-debug'
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR    Traceback (most recent call last):
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR      File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR        rv = self.dispatch_request()
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR      File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR        return self.view_functions[rule.endpoint](**req.view_args)
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR      File "./pschedulerapiserver/debug.py", line 77, in debug
Apr  2 15:58:14 res-dtn journal: pscheduler-api ERROR    IOError: [Errno 2] No such file or directory: '/run/pscheduler-server/pscheduler-api-debug'

```

From: perfsonar-user-request@internet2.edu [mailto:perfsonar-user-request@internet2.edu] On Behalf Of Fligor, Debbie
Sent: Tuesday, April 2, 2019 11:05 PM
To: perfsonar-user@internet2.edu
Cc: Fligor, Debbie <fligor@illinois.edu>
Subject: [perfsonar-user] debugging pscheduler

**Comment by mfeit-internet2** [comment]
This was cleaned up and will be released in 4.2.0.
