### ISSUE TITLE
Cold Boot Should Clear Heartbeats

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#875]
Saw this during a cold start:

```
safe_run/ticker ERROR    Program threw an exception after 0:00:00.069066
safe_run/ticker ERROR    Exception: UniqueViolation: duplicate key value violates unique constraint "heartbeat_pkey"
safe_run/ticker ERROR    DETAIL:  Key (name)=(runner) already exists.
safe_run/ticker ERROR    CONTEXT:  SQL statement "INSERT INTO heartbeat (name)
safe_run/ticker ERROR        VALUES
safe_run/ticker ERROR            ('ticker'),
safe_run/ticker ERROR    #011('scheduler'),
safe_run/ticker ERROR    #011('runner'),
safe_run/ticker ERROR    #011('archiver')"
safe_run/ticker ERROR    PL/pgSQL function heartbeat_cold_boot() line 4 at SQL statement
safe_run/ticker ERROR    SQL statement "SELECT heartbeat_cold_boot()"
safe_run/ticker ERROR    PL/pgSQL function cold_boot() line 3 at PERFORM
safe_run/ticker ERROR
safe_run/ticker ERROR    Traceback (most recent call last):
safe_run/ticker ERROR      File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 73, in safe_run
safe_run/ticker ERROR        function()
safe_run/ticker ERROR      File "/usr/libexec/pscheduler/daemons/ticker", line 170, in <lambda>
safe_run/ticker ERROR        pscheduler.safe_run(lambda: main_program())
safe_run/ticker ERROR      File "/usr/libexec/pscheduler/daemons/ticker", line 132, in main_program
safe_run/ticker ERROR        cursor.execute("SELECT cold_boot()")
safe_run/ticker ERROR    UniqueViolation: duplicate key value violates unique constraint "heartbeat_pkey"
safe_run/ticker ERROR    DETAIL:  Key (name)=(runner) already exists.
safe_run/ticker ERROR    CONTEXT:  SQL statement "INSERT INTO heartbeat (name)
safe_run/ticker ERROR        VALUES
safe_run/ticker ERROR            ('ticker'),
safe_run/ticker ERROR    #011('scheduler'),
safe_run/ticker ERROR    #011('runner'),
safe_run/ticker ERROR    #011('archiver')"
safe_run/ticker ERROR    PL/pgSQL function heartbeat_cold_boot() line 4 at SQL statement
safe_run/ticker ERROR    SQL statement "SELECT heartbeat_cold_boot()"
safe_run/ticker ERROR    PL/pgSQL function cold_boot() line 3 at PERFORM
safe_run/ticker ERROR    Waiting 0.75 seconds before restarting
```

Should probably do an upsert in case any of the daemons are already running.

**Comment by mfeit-internet2** [comment]
Not critical; bumping to 4.3.
