### ISSUE TITLE
Handle better failing archiver processes

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#985]
When an archiver server is failing, or not even started, there is little debug information available.  I was trying to debug the esmond-archiver, but it was not even starting and all I got by turning debug on the pscheduler-archiver is something like:

```
May  1 18:00:33 psd9 archiver DEBUG    8: Archiving to esmond: {'task-href': […some…more…data…removed…], 'attempts': 0}
May  1 18:00:33 psd9 archiver DEBUG    Pool esmond: New process 1
May  1 18:00:33 psd9 archiver DEBUG    Pool esmond: Got a process
May  1 18:00:33 psd9 archiver DEBUG    Waiting 15.0 for change or notification
May  1 18:00:33 psd9 archiver DEBUG    8: Returned JSON from archiver: None
May  1 18:00:33 psd9 archiver DEBUG    Exception: AttributeError: 'NoneType' object has no attribute 'get'
May  1 18:00:33 psd9 archiver DEBUG    Traceback (most recent call last):
May  1 18:00:33 psd9 archiver DEBUG      File "/usr/lib/pscheduler/daemons/archiver", line 555, in run
May  1 18:00:33 psd9 archiver DEBUG        self.__run()
May  1 18:00:33 psd9 archiver DEBUG      File "/usr/lib/pscheduler/daemons/archiver", line 714, in __run
May  1 18:00:33 psd9 archiver DEBUG        "stderr": result.get("error", "")
May  1 18:00:33 psd9 archiver DEBUG    AttributeError: 'NoneType' object has no attribute 'get'
May  1 18:00:33 psd9 archiver DEBUG    8: Thread finished
```

 It would be nice to know a bit more what is failing in this kind of situation.

**Comment by mfeit-internet2** [comment]
This is the result result of a bug in the archiver program causing an exception to be thrown.  That's about the best message for that circumstance.

I've fixed the problem that caused it.
